#!/bin/sh
# /opt/etc/init.d/S99neofit
#chmod +x  /opt/etc/init.d/S99neofit
# 💡 Управление NeoFit для sing-box: установка, удаление, проверка, интерфейсы и т.д. допиливаю до идеала))

ACTION="$1"

# 🛠 Проверка симлинка neofit
# 🛠 Создаём симлинк на себя
SCRIPT_PATH="$(readlink -f "$0")"
mkdir -p /opt/bin
ln -sf "$SCRIPT_PATH" /opt/bin/neofit && \
  printf "[⚙️] Введите для подсказки: neofit\n"

# Определение IP-адреса локального интерфейса br0
ip_address=$(ip addr show br0 | grep 'inet ' | awk '{print $2}' | cut -d/ -f1)

# Цвета
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_ok()   { echo -e "${GREEN}[✅]${NC} $1"; logger -t S99neofit "✅ $1"; }
log_warn() { echo -e "${YELLOW}[⚠️]${NC} $1"; logger -t S99neofit "⚠️ $1"; }
log_err()  { echo -e "${RED}[❌]${NC} $1" >&2; logger -t S99neofit "❌ $1"; }
log()      { echo -e "${GREEN}[ℹ️]${NC} $1"; logger -t S99neofit "ℹ️ $1"; }

if [ -z "$ip_address" ]; then
  log_err "⚠️Не удалось определить IP br0 — проверьте, что интерфейс существует"
  exit 1
fi

entware_silent() { "$@" >/dev/null 2>&1; }
ndmc_silent() {
  ndmc -c "$1" >/dev/null 2>&1
}

check_status() {
  STATUS=$(/opt/etc/init.d/S99sing-box status)
  if echo "$STATUS" | grep -qi "alive"; then
    log_ok "🔜 sing-box ✅работает:\n $STATUS"
  elif echo "$STATUS" | grep -qi "dead"; then
    log_err "🔜 sing-box ❌НЕ запущен:\n $STATUS"
  else
    log_warn "🔜 sing-box ⚠️Ошибка:\n $STATUS"
  fi
}

if [ "$ACTION" = "start" ] || [ "$ACTION" = "restart" ]; then
  log_warn "🗑️ Удаляю link интерфейса opkgtun0"
  entware_silent /opt/sbin/ip link delete opkgtun0
  log_warn "🔄 Перезапускаю службу sing-box"
  entware_silent /opt/etc/init.d/S99sing-box restart
  sleep 2
  check_status
  exit 0
fi

if [ "$ACTION" = "status" ]; then
  check_status
  exit 0
fi

if [ "$ACTION" = "stop" ]; then
  log_warn "❌Останавливаю службу sing-box"
  entware_silent /opt/etc/init.d/S99sing-box stop
  sleep 2
  check_status
  exit 0
fi

log_warn "$0 \nДоступные команды: neofit {start|stop|restart|status}\nНаш канал: t.me/neofitkeenetic \nНаш чат: t.me/+f_8QmNYgg180Njg6 \nGitHub: github.com/pegakmop/neofit"
exit 1
