#!/bin/sh
# Универсальный init-скрипт для Keenetic / Entware
# Автозапуск, остановка, рестарт и статус по общему имени neofit

ENABLED=yes
NAME="neofit"
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func

LINK="/opt/bin/${NAME}"
[ -L "$LINK" ] && [ ! -e "$(readlink -f "$LINK")" ] && rm -f "$LINK"
if [ ! -L "$LINK" ]; then
    ln -sf "$0" "$LINK"
    echo "Created symlink: $LINK -> $0"
    echo "${NAME} {start|stop|restart|status}"
fi

start() {
    ( /opt/bin/${NAME}xray >/dev/null 2>&1 & )
    ( /opt/bin/${NAME}sb   >/dev/null 2>&1 & )
    echo "Starting ${NAME}xray and ${NAME}sb..."
    sleep 3
    ps | grep "$NAME" | grep -v grep
    echo "Если не запустилось должно быть пусто..."
}

stop() {
    ps | grep "$NAME" | grep -v grep | awk '{print $1}' | xargs kill -9 2>/dev/null
    echo "Stopping ${NAME} processes..."
    ps | grep "$NAME" | grep -v grep
    echo "Если остановлен должно быть пусто..."
}

status() {
    echo "Checking ${NAME} processes..."
    ps | grep "$NAME" | grep -v grep
    echo "Если остановлен должно быть пусто..."
}

case "$1" in
    start|"")
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 1
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        ;;
esac

exit 0
